server:
  port: 8763
spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/bsmmdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone = GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registry-fetch-interval-seconds: 10 # 拉取服务注册信息间隔（缺省为30s）
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
fatTigger:
  absolutePath: G:\\downloadfile\\
  relativePath: G:\\downloadfile\\
  propertiesFileName: test.properties